version: '3.8'

services:
  app:
    build: .
    container_name: proditec-app
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./src:/app/src
      - ./locales:/app/locales
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m src.main --scraper basic # Default command, change as needed
  
  dashboard:
    build: .
    container_name: proditec-dashboard
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./src:/app/src
    ports:
      - "8501:8501"
    command: streamlit run src/compara_emails.py --server.address=0.0.0.0
